[package]
name = "YouTubeChannelsInfoParser"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["blocking"] }
scraper = "0.20.0"
csv = "1.3.0"
serde_json = "1.0.128"
isocountry = "0.3.2"
serde = { version = "1.0", features = ["derive"] }

